#!/usr/bin/env bash

# This script is run automatically by the Nexus Updater whenever smart-heard is 
# installed or updated.
# It moves the files and scripts into the correct locations and runs any other 
# housekeeping scripts.

# Version 0.0.1

# Make a folder in the user's home folder if it doesn't already exist
SMART_HEARD_ROOT="$HOME/WB7FHC"
mkdir -p $SMART_HEARD_ROOT

SCRIPT_PATH="${SMART_HEARD_ROOT}/smart_heard.sh"

# Install latest script
cp -f smart-heard/*.sh ${SMART_HEARD_ROOT}/

# Manage the fsq_names.csv file
if [[ -s ${SMART_HEARD_ROOT}/fsq_names.csv ]]
then 
	# User already has a fsq_names.csv file
	# Run merge script to combine latest CSV file with user's CSV file
	: # Replace ':' with the name of the merge script
else 
	# Install the repo's CSV file since none exists in $SMART_HEARD_ROOT
	cp -f smart-heard/*.csv ${SMART_HEARD_ROOT}/
fi

# Manage the smart_heard.list file
if [[ -s ${SMART_HEARD_ROOT}/smart_heard.list ]]
then
	# Note sure what to do here... Maybe nothing?
	:
else # Install the repo's list file since none exists in $SMART_HEARD_ROOT
	cp -f smart-heard/*.list ${SMART_HEARD_ROOT}/
fi

# Add script to Fldigi autostart if it's not already set up.
for SIDE in '' -left -right
do
	# Make sure fldigi config file exists.
	[[ -s $HOME/.fldigi${SIDE}/fldigi_def.xml ]] || continue
	# Check if smart_heard autostart already configured
	grep -q "AUTO_PROG.*smart_heard" $HOME/.fldigi${SIDE}/fldigi_def.xml && continue
	# smart_heard not in autostart. Add it to an open autostart slot
	# There are 3 autostart slots in Fldigi
	ADDED=false
	for I in $(seq 1 3)
	do
		if grep -q "AUTO_PROG${I}_PATHNAME><" $HOME/.fldigi${SIDE}/fldigi_def.xml
		then
			# Found an open autostart slot. Insert smart_heard.sh
			[[ $SIDE =~ right ]] && $SCRIPT_PATH="$SCRIPT_PATH right"
			sed -i \
				-e "s/<AUTO_PROG${I}_PATHNAME></<AUTO_PROG${I}_PATHNAME>$SCRIPT_PATH</" \
				-e "s/<PROG${I}_AUTO_ENABLE>.*</<PROG${I}_AUTO_ENABLE>1</" \
			$HOME/.fldigi${SIDE}/fldigi_def.xml
			ADDED=true
			break
		fi
	done
	[[ $ADDED == false ]] && echo >&2 "WARNING: No open autostart slot to add smart_heard.sh to $SIDE radio!"
done
