#!/usr/bin/env bash

# This script is run automatically by the Nexus Updater whenever smart-heard is 
# installed or updated.
# It moves the files and scripts into the correct locations and runs any other 
# housekeeping scripts.

VERSION="1.0.0"

#----------------------------------------------------------------------------
# Make a WB7FHC folder in the user's home folder if it doesn't already exist
SMART_HEARD_ROOT="${HOME}/WB7FHC"
mkdir -p $SMART_HEARD_ROOT
SCRIPT_PATH="${SMART_HEARD_ROOT}/smart_heard.sh"

# Install latest script and files
cp -f smart-heard/*.sh ${SMART_HEARD_ROOT}/
cp -f smart-heard/*.skin ${SMART_HEARD_ROOT}/
#cp -f smart-heard/*.desktop $HOME/.local/share/applications/
sudo cp -f smart-heard/*.png /usr/share/pixmaps/
# When the user runs the smart heard script for the first time after updating, 
# it'll ask the user whether to overwrite their existing CSV file with the 
# downloaded CSV file. So, the following line is commented out.
# cp -f smart-heard/*.csv ${SMART_HEARD_ROOT}/

# Stop Fldigi and smart_heard.sh if running
(pgrep -x fldigi &>/dev/null) && pkill -SIGTERM -x fldigi
(pgrep -x smart_heard.sh &>/dev/null) && pkill -SIGTERM -x smart_heard.sh

#----------------------------------------------------------------------------
# Add smart_heard.sh to Fldigi autostart if it's not already set up.
# Check "normal" (~/.fldigi), left (~/.fldigi-left), and right (~/.fldigi-right) 
# fldigi instance autostart settings
LXTERM="lxterminal --geometry=52x30 -e "
for SIDE in '' -left -right
do
	###################################################
	# Enable RX/TX logging if not already enabled
	if [[ -s $HOME/.fldigi${SIDE}/fldigi.prefs ]] && \
		grep -q -E "^log_enabled:0" $HOME/.fldigi${SIDE}/fldigi.prefs
	then
		echo >&2 "Enabling RX/TX logging in fldigi${SIDE}"
		sed -i -e "s/^log_enabled:0/log_enabled:1/" $HOME/.fldigi${SIDE}/fldigi.prefs
	else
		echo >&2 "RX/TX logging already enabled in fldigi${SIDE}"
	fi

	###################################################
	# Proceed only if fldigi config file exists.
	[[ -s $HOME/.fldigi${SIDE}/fldigi_def.xml ]] || continue

	###################################################
	# Enable FSQ heard log if not already enabled
	if grep -q -E "<FSQ_ENABLE_HEARD_LOG>1<" $HOME/.fldigi${SIDE}/fldigi_def.xml && \
		grep -q -E "<FSQ_HEARD_LOG>fsq_heard_log.txt<" $HOME/.fldigi${SIDE}/fldigi_def.xml
	then
		# FSQ heard log already enabled
		echo >&2 "FSQ heard log already enabled on fldigi${SIDE}"
		continue
	else
		# Enable FSQ heard log and set log file name
		echo >&2 "Enabling FSQ heard log on fldigi${SIDE}"
		sed -i \
			-e "s+<FSQ_ENABLE_HEARD_LOG>.*<+<FSQ_ENABLE_HEARD_LOG>1<+" \
			-e "s+<FSQ_HEARD_LOG>.*<+<FSQ_HEARD_LOG>fsq_heard_log.txt<+" \
			   $HOME/.fldigi${SIDE}/fldigi_def.xml	
	fi

	###################################################
	# Check if smart_heard autostart already configured
	ADDED_AUTOSTART=false
	if grep -q -E "AUTO_PROG.*${SCRIPT_PATH}" $HOME/.fldigi${SIDE}/fldigi_def.xml
	then
		echo >&2 "smart_heard already in autostart in fldigi${SIDE}"
		ADDED_AUTOSTART=true
		continue
	fi
	# smart_heard not in one of the autostart slots.
	# There are 3 autostart slots in Fldigi. Look for an open slot.
	for I in $(seq 1 3)
	do
		if grep -q "AUTO_PROG${I}_PATHNAME><" $HOME/.fldigi${SIDE}/fldigi_def.xml
		then
			# Found an open autostart slot. Insert smart_heard.sh
			# Add 'right' argument if we're processing the right Fldigi configuration
			echo >&2 "Adding smart_heard to autostart in fldigi${SIDE}"
         if [[ $SIDE =~ right ]]
         then
            AUTOSTART="\"$SCRIPT_PATH right\""
         else
            AUTOSTART="\"$SCRIPT_PATH\""
         fi
			sed -i \
				-e "s+<AUTO_PROG${I}_PATHNAME><+<AUTO_PROG${I}_PATHNAME>${LXTERM}${AUTOSTART}<+" \
				-e "s+<PROG${I}_AUTO_ENABLE>.*<+<PROG${I}_AUTO_ENABLE>1<+" \
			   $HOME/.fldigi${SIDE}/fldigi_def.xml
			ADDED_AUTOSTART=true
			break
		fi
	done
	if [[ $ADDED_AUTOSTART == false ]]
   then
   	MSG="WARNING: No open autostart slot found to add smart_heard.sh to Fldigi${SIDE}!\nAdd smart_heard manually to Fldigi's autostart configuration."
		if xhost &>/dev/null
		# We have an X session, so it's safe to use yad
		then
			yad --center --title="smart_heard.sh installation WARNING" --info --borders=20 \
				--buttons-layout=center --text-align=center \
				--text="<big><b>${MSG}</b></big>\n" \
				--button="OK":0
		else
			# X is not running. Print to console
			  echo -e >&2 "$MSG"
		fi
	fi
done

